version: '3'
services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    hostname: discovery-service
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    hostname: gateway-service
    depends_on:
      - email-service
      - push-service
      - sms-service
    ports:
      - '9095:9095'
    entrypoint: ["/opt/services/wait-for","http://discovery-service:8761","-t","60","--","java","-jar","/opt/services/gateway-service.jar"]
  push-service:
    build:
      context: ./push-service
      dockerfile: Dockerfile
    hostname: push-service
    depends_on:
      - discovery-service
    volumes:
      - logs:/opt/services/log/
    environment:
      - SERVICE_ROOT=/opt/services
    entrypoint: ["/opt/services/wait-for","http://discovery-service:8761","-t","60","--","java","-jar","/opt/services/push-service.jar"]
  sms-service:
    build:
      context: ./sms-service
      dockerfile: Dockerfile
    hostname: sms-service
    depends_on:
      - discovery-service
    volumes:
      - logs:/opt/services/log/
    environment:
      - SERVICE_ROOT=/opt/services
    entrypoint: ["/opt/services/wait-for","http://discovery-service:8761","-t","60","--","java","-jar","/opt/services/sms-service.jar"]
  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    hostname: email-service
    depends_on:
      - discovery-service
    volumes:
      - logs:/opt/services/log/
    environment:
      - SERVICE_ROOT=/opt/services
    entrypoint: ["/opt/services/wait-for","http://discovery-service:8761","-t","60","--","java","-jar","/opt/services/email-service.jar"]
volumes:
  logs: