server:
  port: 9092
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

eureka:
  instance:
    hostname: email-service
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka

spring:
  application:
    name: email-service
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  jackson:
    default-property-inclusion: non_null